### ISSUE TITLE
[BUG] Your website can't register

### ISSUE THREAD

**Issue by af913337456** [infobip-community/infobip-api-go-sdk#61]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by af913337456** [comment]
keep loading

<img width="1030" alt="图片" src="https://github.com/infobip-community/infobip-api-go-sdk/assets/10436277/15ffef5c-1134-42b2-9af6-0de3b8abccec">

**Comment by ukmadlz** [comment]
HI @af913337456, I believe this was resolved. If you're still having issues accessing the Infobip, please contact support@infobip.com

I'll close this issue as this isn't a library specific bug
