### ISSUE TITLE
[BUG] WhatsApp send Template function validation restrict numbers on the template name

### ISSUE THREAD

**Issue by godinezseba** [infobip-community/infobip-api-go-sdk#65]
**Describe the bug**
In our company we create some WhatsApp templates with the following structure: _template_event_name_version_ where version is a **number**. It works to create the template on Infobip and works to send messages using the [API](https://www.infobip.com/docs/api/channels/whatsapp/whatsapp-outbound-messages/send-whatsapp-template-message) but when we try to send the same message with the [SendTemplate](https://pkg.go.dev/github.com/infobip-community/infobip-api-go-sdk/v3@v3.3.1/pkg/infobip/whatsapp#WhatsApp.SendTemplate) function we get this error: `Field validation for 'templateName' failed on the 'templatenamenotsnakecase' tag` 

**To Reproduce**
1. Create the request with [models.WATemplateMsgs](https://pkg.go.dev/github.com/infobip-community/infobip-api-go-sdk/v3@v3.3.1/pkg/infobip/models#WATemplateMsgs).
2. Set the [templateName](https://pkg.go.dev/github.com/infobip-community/infobip-api-go-sdk/v3@v3.3.1/pkg/infobip/models#TemplateMsgContent) as `lider_whatsapp_test_infobip_10`.
3. Use [client.WhatsApp.SendTemplate](https://pkg.go.dev/github.com/infobip-community/infobip-api-go-sdk/v3@v3.3.1/pkg/infobip/whatsapp#WhatsApp.SendTemplate) function to send the message.
4. See error: `Field validation for 'templateName' failed on the 'templatenamenotsnakecase' tag` 

**Expected behavior**
The SDK should send the message with that template name, because the API send the same message.

**Desktop (please complete the following information):**
 - Version [v3.3.1](https://github.com/infobip-community/infobip-api-go-sdk/tree/v3.3.1) I belive on GitHub says 3.1.1

**Additional context**
We need to have the version number on the name of the templates because they are always changing.

**Comment by godinezseba** [comment]
I want to complement that I think the error is because the templateName has a **number** because if I send a message with a templateName `lider_whatsapp_test_infobip` the function sends the message.

**Comment by strosek** [comment]
Thank you for spotting the bug @godinezseba! I'll soon upload a fix.

**Comment by strosek** [comment]
Hi @godinezseba The fix is implemented in the PR linked above, waiting for a review. ETA Monday, Dic 4.
