### ISSUE TITLE
[BUG] WhatsApp send Template function validation restrict numbers of buttons to 3

### ISSUE THREAD

**Issue by paz52** [infobip-community/infobip-api-go-sdk#76]
**Describe the bug**
In out company, we created some WhatsApp templates with up to 10 buttons (since the [platform](https://www.infobip.com/docs/api/channels/whatsapp/whatsapp-service-management/create-whatsapp-template) allows it), but when testing the templates with more than 3 buttons, an error occurs during validation. 

**To Reproduce**
1. Create the request with [models.WATemplateMsgs](https://pkg.go.dev/github.com/infobip-community/infobip-api-go-sdk/v3@v3.3.1/pkg/infobip/models#WATemplateMsgs).
2. Set the template with a  [list of buttons](https://pkg.go.dev/github.com/infobip-community/infobip-api-go-sdk/v3@v3.3.1/pkg/infobip/models#TemplateStructure) containing 4 or more elements.
3. Use [client.WhatsApp.SendTemplate](https://pkg.go.dev/github.com/infobip-community/infobip-api-go-sdk/v3@v3.3.1/pkg/infobip/whatsapp#WhatsApp.SendTemplate) function to send the message.
4. See error: `Field validation for 'Buttons' failed on the 'max' tag`.

**Expected behavior**
The expected behavior would be that the WhatsApp message is sent with the 4 or more buttons. 

**Desktop (please complete the following information):**
 - OS: MAC
 - Browser: Chrome
 - Infobip Version [v3.4.1](https://github.com/infobip-community/infobip-api-go-sdk/tree/v3.4.1)

**Comment by lvukadinovic-ib** [comment]
Hi @paz52,

thank you for using our library and noticing the bug.
We will investigate this and keep you posted.

Kind regards,
Luka Vukadinović

**Comment by lvukadinovic-ib** [comment]
Hi @paz52 ,

we've released the new version (3.4.2) and the issue should be fixed. 
Please let's us know if it still persists.

Kind regards,
Luka Vukadinović

**Comment by paz52** [comment]
Hi @lvukadinovic-ib, 
We updated the Go SDK to v3.4.2 and tested with a template that has 4 buttons, and it worked perfectly. 

Thanks a lot for your help. 

Best regards, 
Paz.
